### ISSUE TITLE
UI change color of Application

### ISSUE THREAD

**Issue by sharkey1314** [CS2103JAN2017-W09-B2/main#15]
Experiment with how to design Application using JavaFX
1. Colors
2. Position
3. Background picture
4. Logo

**Comment by sharkey1314** [comment]
Yongsiang maybe can change the colors to fit our color scheme used for our logo! Need close all issues for milestone thanks!

**Comment by YongSiang94** [comment]
Ya doing the color scheme thing tomorrow. But don't think will be using light pink as the scheme. Our logo now is a light grey background.
