### ISSUE TITLE
V0.3 feedback

### ISSUE THREAD

**Issue by jeffryhartanto** [CS2103JAN2017-W09-B2/main#50]
# User Guide
- Good job for writing `About Me` section.
- `Command Summary` link does not work.
- Good job adding some screen shots.
- Numbering typo in Features 3.2
- Consider putting the example after the Format. If your example is good enough, then the user does not need to read the description.
- `...` or `..` ?? :)
- The format and title for 3.4.4 does not include `by` for specifying date? Can it accept `edit 1 buy something by #`?
- Example for `undo all` is mis-match.
- Some listed commands in the Command Summary are not in Features section.
- In practice, it's better to match the implemented features in v0.3 with the User Guide. Imagine the user might try typing those unavailable commands.
- `Features` link in `FAQ` does not work.
- See if you can make the command format easier to type.
- The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.
- Assuming you have added `add event feature` then you guys are well on your way to meet module expectations of the project. Great job.

# Developer Guide 
- Link 1 to 5 do not work.
- Diagrams haven't been updated.
- Suggested additions:
  - Explain how your design support undo/redo. There are multiple ways this can be done, so it will be useful to explain how you do it and why you chose to do it that way.
  - Similarly, you can explain other interesting design decisions you made.
- You guys listed a lot of uses cases, but make sure/double-check that you have implemented the `must-have-features`.
- `MSS` should capture back-and-forth interaction between user and the system, so it doesn't make sense to have 2 or more consecutive steps done by the user or the system. E.g. `User keys in a series of command(s)` is not necessary.
- `Should be stored as a local copy.`, are you sure this is a NFR?

**Comment by pyxyyy** [comment]
**Comments to be ported over to V0.4 feedback:**
- 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.

- Diagrams haven't been updated.

- Suggested additions:
Explain how your design support undo/redo. There are multiple ways this can be done, so it will be useful to explain how you do it and why you chose to do it that way.
Similarly, you can explain other interesting design decisions you made.

The remaining comments are resolved.
