### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by sharkey1314** [CS2103JAN2017-W09-B2/main#6]
Details: 
1. Update it to match our project

**Comment by sharkey1314** [comment]
Also, remember to acknowledge the original source of the code i.e. The sample project created by SE-EDU initiative at https://github.com/se-edu/
++ Need picture of UI saved as doc/images/Ui.png

**Comment by YongSiang94** [comment]
Picture is done. Need to have the destination referring to the picture.

*PS* Need to edit the picture a little as today's discussion.

**Comment by sharkey1314** [comment]
You can close the issue once you're done! Then we can close milestone V0.1 👍
