### ISSUE TITLE
Implement Load feature

### ISSUE THREAD

**Issue by pyxyyy** [CS2103JAN2017-W09-B2/main#63]
More importantly, should be able to **save to wherever that is specified**, i.e. after saving if you continue to add, the new changes are reflected in the new location.

**Comment by YongSiang94** [comment]
Left storage part of the LoadCommand

**Comment by YongSiang94** [comment]
Changed name to ImportCommand

**Comment by YongSiang94** [comment]
Changed name to SaveCommand
